[build]
builder = "dockerfile"

[deploy]
startCommand = "python server.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "8000" 