name: Birdwatcher Ecommerce Summary

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9:00 UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  ecommerce-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: tinybirdco/ai@main
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          resend_api_key: ${{ secrets.RESEND_API_KEY }}
          google_application_credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          vertex_api_key: ${{ secrets.VERTEX_API_KEY }}
          google_cloud_project: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          google_cloud_location: ${{ secrets.GOOGLE_CLOUD_LOCATION }}
          tinybird_token: ${{ secrets.TINYBIRD_TOKEN }}
          tinybird_host: ${{ secrets.TINYBIRD_HOST }}
          prompt: |
            Run the analysis and email to cameronarcher@tinybird.co
          mission: ecommerce_daily_summary
          model: 'gemini-2.0-flash'
